# Generated by Django 3.2.10 on 2022-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='contact',
        ),
        migrations.AddField(
            model_name='unit',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
