# Generated by Django 3.2.4 on 2021-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gu', '一般使用者'), ('uu', '單位帳號'), ('ua', '單位管理員'), ('sa', '系統管理員'), ('de', '開發者/superuser')], default='gu', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, choices=[('taibif', 'TaiBIF'), ('tesri', '特生中心'), ('tfri', '林試所'), ('oca', '海保署'), ('cpami', '營建署'), ('forest', '林務局'), ('tbia', 'TBIA')], default=None, max_length=20),
        ),
    ]
