# Generated by Django 3.2.10 on 2022-01-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220118_0719'),
        ('account', '0003_auto_20220118_0658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Partner',
        ),
        migrations.AlterModelTable(
            name='partner',
            table='partner',
        ),
    ]
