# Generated by Django 3.2.4 on 2021-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210629_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('taibif', 'TaiBIF'), ('tesri', '特生中心'), ('tfri', '林試所'), ('oca', '海保署'), ('cpami', '營建署'), ('forest', '林務局'), ('tbia', 'TBIA')], default=None, max_length=20, null=True),
        ),
    ]
