# Generated by Django 3.2.10 on 2022-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220118_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
