# Generated by Django 3.2.10 on 2022-01-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220119_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='title',
        ),
    ]
