# Generated by Django 3.2.4 on 2021-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('none', '無'), ('taibif', 'TaiBIF'), ('tesri', '特生中心'), ('tfri', '林試所'), ('oca', '海保署'), ('cpami', '營建署'), ('forest', '林務局'), ('tbia', 'TBIA')], default='none', max_length=20),
        ),
    ]
