version: '3.7'

services:
  web:
    build: .
    container_name: tbia-web-dev-container
    image: tbia-web-dev-image
    ports:
      - 8000:8000
    depends_on:
      - postgres
    # links:
    #   - postgres:postgres
    volumes:
      - .:/code
      - ../tbia-volumes/static:/tbia-volumes/static
      - ../tbia-volumes/bucket:/tbia-volumes/bucket
      - ../tbia-volumes/media:/tbia-volumes/media
      - ../tbia-volumes/solr:/tbia-volumes/solr
    # command: "./scripts/wait-for-it.sh db:5432 -t 5 -- ./scripts/docker-web-dev-entry.sh"
    #command: "./scripts/wait-for-it.sh db:5432 -t 5 -- ./scripts/docker-web-entry.sh"
    restart: always
    env_file:
      - .env
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tbia
    command: /srv/start
  postgres:
    # build: ./postgres
    container_name: tbia-db-container
    image: postgres:13-alpine
    restart: always
    volumes:
      - ../tbia-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../tbia-volumes/bucket:/tbia-volumes/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tbia
      - PGDATA=/var/lib/postgresql/data/pgdata
  # redis:
  #   image: redis:5-alpine
  #   restart: always
  solr:
    build: ./solr-workspace
    image: solr:8.11.1
    container_name: tbia-solr
    ports:
      - "8983:8983"
    restart: always
    volumes:
      - ../tbia-volumes/solr:/var/solr
      - ./solr-workspace/:/workspace
      # - ./solr-workspace/solr.in.sh.orig:/opt/solr-8.11.1/bin/solr.in.sh.orig
      # - ./file/:/file
      # command:
      #   - solr-precreate
      #   - gettingstarted
      #   - bash
