services:
  web:
    platform: linux/amd64
    build: .
    container_name: tbia-web-dev-container
    image: tbia-web-dev-image
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../tbia-volumes/static:/tbia-volumes/static
      - ../tbia-volumes/bucket:/tbia-volumes/bucket
      - ../tbia-volumes/media:/tbia-volumes/media
      - ../tbia-volumes/solr:/tbia-volumes/solr
      - ../tbia-volumes/logs:/logs
    restart: always
    env_file:
      - .env
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tbia
    command: /srv/start
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    platform: linux/amd64
    container_name: tbia-db-container
    image: postgres:13-alpine
    restart: always
    ports:
      - 5431:5432
    volumes:
      - ../tbia-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../tbia-volumes/bucket:/tbia-volumes/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tbia
      - PGDATA=/var/lib/postgresql/data/pgdata