networks:
  datahub:
    external: true

services:
  web:
    platform: linux/amd64
    build: .
    container_name: tbia-web-dev-container
    image: tbia-web-dev-image
    ports:
      - 127.0.0.1:8100:8100
    depends_on:
      - postgres-web
    volumes:
      - .:/code
      - ../tbia-volumes/static:/tbia-volumes/static
      - ../tbia-volumes/bucket:/tbia-volumes/bucket
      - ../tbia-volumes/media:/tbia-volumes/media
      - ../tbia-volumes/solr:/tbia-volumes/solr
      - ../tbia-volumes/logs:/logs
    restart: always
    env_file:
      - .env
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres-web
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
    command: /srv/start
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - datahub
  postgres-web:
    platform: linux/amd64
    container_name: tbia-db-container
    image: postgres:13-alpine
    restart: always
    networks:
      - datahub
    volumes:
      - ../tbia-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../tbia-volumes/bucket:/tbia-volumes/bucket
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata