from django.urls import path

from . import views

urlpatterns = [
    path('google/callback', views.get_auth_callback, name='get_auth_callback'),
    path('verify-user/<uidb64>/<token>', views.verify_user, name='verify'),
    path('verify-reset-password/<uidb64>/<token>', views.verify_reset_password, name='verify_reset_password'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('reset_password_submit', views.reset_password_submit, name='reset_password_submit'),
    path('send_reset_password', views.send_reset_password, name='send_reset_password'),
    path('register', views.register, name='register'),
    path('register/verification', views.register_verification, name='register_verification'),
    path('register/success', views.register_success, name='register_success'),
    path('register/resend/verification', views.resend_verification_email, name='resend_verification_email'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('manager', views.manager, name='manager'),
    path('update_personal_info', views.update_personal_info, name='update_personal_info'),
    path('update_user_status', views.update_user_status, name='update_user_status'),
    path('manager/partner', views.manager_partner, name='manager_partner'),
    path('manager/partner/news', views.partner_news, name='partner_news'),
    path('manager/partner/info', views.partner_info, name='partner_info'),
    path('manager/system', views.manager_system, name='manager_system'),
    path('manager/system/news', views.system_news, name='system_news'),
    path('manager/system/info', views.system_info, name='system_info'),
    path('manager/system/keyword', views.system_keyword, name='system_keyword'),
    path('manager/system/resource', views.system_resource, name='system_resource'),
    path('generate_no_taxon_csv', views.generate_no_taxon_csv, name='generate_no_taxon_csv'),
    path('update_partner_info', views.update_partner_info, name='update_partner_info'),
    path('send_partner_request', views.send_partner_request, name='send_partner_request'),
    path('withdraw_partner_request', views.withdraw_partner_request, name='withdraw_partner_request'),
    path('update_keywords', views.update_keywords, name='update_keywords'),
    path('update_tbia_about', views.update_tbia_about, name='update_tbia_about'),
    path('submit_news', views.submit_news, name='submit_news'),
    path('withdraw_news', views.withdraw_news, name='withdraw_news'),
    path('send_feedback', views.send_feedback, name='send_feedback'),
    path('update_feedback', views.update_feedback, name='update_feedback'),
    path('get_request_detail', views.get_request_detail, name='get_request_detail'),
    path('change_manager_page', views.change_manager_page, name='change_manager_page'),
]
