# Generated by Django 3.2.4 on 2021-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='name_author',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='simple_name',
        ),
        migrations.AddField(
            model_name='taxon',
            name='formatted_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
