# Generated by Django 3.2.4 on 2021-08-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210831_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='alternative_name_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='misapplied',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
