# Generated by Django 3.2.4 on 2021-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210831_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='id',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='tbiaUUID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
