# Generated by Django 3.2.4 on 2021-08-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210831_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='originalCreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='originalModified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='originalCreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='originalModified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
