# Generated by Django 3.2.4 on 2021-09-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210831_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='tbiaUUID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
