# Generated by Django 3.2.4 on 2021-09-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210901_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='ResourceContacts',
            new_name='resourceContacts',
        ),
    ]
