# Generated by Django 3.2.10 on 2022-10-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_resourcecontacts_collection_resourcecontacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Occurrence',
        ),
        migrations.DeleteModel(
            name='taxon',
        ),
    ]
