# Generated by Django 3.2.10 on 2022-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0010_auto_20221027_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_name_id', models.CharField(max_length=100)),
                ('namecode', models.CharField(max_length=100)),
            ],
        ),
    ]
