# Generated by Django 3.2.10 on 2022-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_taxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='taxonID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
