# Generated by Django 3.2.10 on 2023-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_taxon_taxonid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetName', models.CharField(max_length=1000)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
    ]
