# Generated by Django 3.2.10 on 2023-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_rename_datasetname_datasetkey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetkey',
            name='record_type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
