# Generated by Django 3.2.10 on 2023-03-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_datasetkey_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecode',
            name='taieol_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
