# Generated by Django 3.2.10 on 2023-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_namecode_taieol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='aberration_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='form_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='hybridformula_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='morph_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='nothosubspecies_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='nothovariety_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='race_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='specialform_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='stirp_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='subform_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='subspecies_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='subvariety_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='variety_c',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
