# Generated by Django 3.2.10 on 2023-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20230410_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='name_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
