# Generated by Django 3.2.10 on 2023-05-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_taxon_name_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='cites',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='iucn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='protected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='redlist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='sensitive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
