# Generated by Django 3.2.10 on 2023-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20230516_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('accepted_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('accepted_common_name_c', models.CharField(blank=True, max_length=10000, null=True)),
                ('accepted_alternative_name_c', models.CharField(blank=True, max_length=10000, null=True)),
                ('name_status', models.CharField(blank=True, max_length=20, null=True)),
                ('taxonID', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
