# Generated by Django 3.2.10 on 2023-10-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='alien_type',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_endemic',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
