# Generated by Django 3.2.10 on 2023-10-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20231011_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetkey',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasetkey',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetkey',
            name='record_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
