# Generated by Django 3.2.10 on 2023-10-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_datasetkey_dataset_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetkey',
            name='dataset_idx',
        ),
        migrations.AddConstraint(
            model_name='datasetkey',
            constraint=models.UniqueConstraint(fields=('name', 'record_type', 'group'), name='dataset_unique'),
        ),
    ]
