# Generated by Django 3.2.10 on 2023-10-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20231013_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetkey',
            old_name='group',
            new_name='rights_holder',
        ),
    ]
