# Generated by Django 3.2.10 on 2023-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20231027_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='is_brackish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_fossil',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_freshwater',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_marine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_terrestrial',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
