# Generated by Django 4.0.4 on 2023-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='char_len',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='char',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='pattern',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
