# Generated by Django 4.0.4 on 2024-01-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_variant_char_len_alter_variant_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
