# Generated by Django 4.0.4 on 2024-01-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_name_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='taxon_name_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
