# Generated by Django 4.0.4 on 2024-01-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_name_taxon_name_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='name',
            constraint=models.UniqueConstraint(fields=('taxonID', 'taxon_name_id'), name='taxonID_taxon_name_id_unique'),
        ),
    ]
