# Generated by Django 4.0.4 on 2025-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_name_taxonid_taxon_name_id_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, max_length=1000, null=True)),
                ('county_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('municipality', models.CharField(blank=True, max_length=1000, null=True)),
                ('municipality_en', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
