# Generated by Django 4.0.4 on 2025-03-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='tbn_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
