# Generated by Django 4.0.4 on 2025-04-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_municipality_tbn_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
