# Generated by Django 4.0.4 on 2025-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
