# Generated by Django 4.0.4 on 2025-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_municipality_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='name',
            name='taxonID_taxon_name_id_unique',
        ),
        migrations.AddConstraint(
            model_name='name',
            constraint=models.UniqueConstraint(fields=('taxonID', 'taxon_name_id', 'name_status'), name='taxonID_taxon_name_id_unique'),
        ),
    ]
