# Generated by Django 3.2.9 on 2021-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(blank=True, choices=[('news', '新聞公告'), ('event', '活動訊息'), ('project', '計畫徵求')], max_length=10, null=True),
        ),
    ]
