# Generated by Django 3.2.9 on 2021-12-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('news', '新聞公告'), ('event', '活動訊息'), ('project', '計畫徵求')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(blank=True, choices=[('strategy', 'TBIA策略文件'), ('guide', '開放資料指引'), ('tool', '參考文件&工具'), ('tutorial', '教學文件')], max_length=10, null=True),
        ),
    ]
