# Generated by Django 3.2.10 on 2022-01-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='unit_id',
            new_name='partner_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='unit_id',
            new_name='partner_id',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='unit_id',
            new_name='partner_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='unit_id',
            new_name='partner_id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='unit_id',
            new_name='partner_id',
        ),
    ]
