# Generated by Django 3.2.10 on 2022-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220922_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='created',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='displayed',
        ),
        migrations.AddField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
