# Generated by Django 3.2.10 on 2022-09-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='attachments',
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
