# Generated by Django 3.2.10 on 2022-10-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220930_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '等待審核'), ('pass', '通過'), ('fail', '不通過'), ('withdraw', '撤回')], max_length=20),
        ),
    ]
