# Generated by Django 3.2.10 on 2022-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_notification_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '下載資料 #0000 已處理完成，請至後台查看'), (2, '有新的意見回饋，請至後台回覆'), (3, '有新的單次使用敏感資料申請 #0000，請至後台審核'), (4, '單次使用敏感資料申請 #0000 審核已完成，請至後台查看'), (5, '有新的單位帳號申請，請至後台審核'), (6, '單位帳號申請審核已完成，請至後台查看'), (7, '有新的最新消息發布申請，請至後台審核'), (8, '最新消息發布審核已完成，請至後台查看')], null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
