# Generated by Django 3.2.10 on 2022-10-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='replied',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(blank=True, choices=[(1, '網頁操作'), (2, '網頁內容'), (3, '聯盟相關')], max_length=10, null=True),
        ),
    ]
