# Generated by Django 3.2.10 on 2022-10-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20221027_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '網頁操作'), (2, '網頁內容'), (3, '聯盟相關')], null=True),
        ),
    ]
