# Generated by Django 3.2.10 on 2022-11-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20221116_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='expired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='download',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
