# Generated by Django 3.2.10 on 2023-01-13 06:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
