# Generated by Django 3.2.10 on 2023-03-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, '網頁操作'), (2, '網頁內容'), (3, '聯盟相關')], null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qa',
            },
        ),
    ]
