# Generated by Django 3.2.10 on 2023-03-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_qa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='content',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='qa',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
