# Generated by Django 3.2.10 on 2023-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20230308_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
