# Generated by Django 3.2.10 on 2023-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_news_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
