# Generated by Django 3.2.10 on 2023-11-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20231011_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='lang',
            field=models.CharField(blank=True, choices=[('en-us', '英文'), ('zh-hant', '中文')], max_length=10, null=True),
        ),
    ]
