# Generated by Django 3.2.10 on 2023-11-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_keyword_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='answer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
