# Generated by Django 4.0.4 on 2023-12-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20231115_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_use_tbia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
