# Generated by Django 4.0.4 on 2024-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_news_author_use_tbia'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='doc_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
