# Generated by Django 4.0.4 on 2024-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_resource_doc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('news', '新聞公告'), ('event', '活動訊息'), ('project', '徵求公告')], max_length=10, null=True),
        ),
    ]
