# Generated by Django 4.0.4 on 2024-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lang',
            field=models.CharField(blank=True, choices=[('en-us', '英文'), ('zh-hant', '中文')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='lang',
            field=models.CharField(blank=True, choices=[('en-us', '英文'), ('zh-hant', '中文')], max_length=10, null=True),
        ),
    ]
