# Generated by Django 4.0.4 on 2024-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_news_lang_resource_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='lang',
            field=models.CharField(choices=[('en-us', '英文'), ('zh-hant', '中文')], default='zh-hant', max_length=10),
        ),
    ]
