# Generated by Django 4.0.4 on 2024-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_news_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
