# Generated by Django 4.0.4 on 2024-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_resource_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
