# Generated by Django 4.0.4 on 2024-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_news_publish_date_alter_resource_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('news', '新聞公告'), ('event', '活動訊息'), ('project', '徵求公告'), ('datathon', '數據松成果')], max_length=10, null=True),
        ),
    ]
