# Generated by Django 4.0.4 on 2024-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
