# Generated by Django 4.0.4 on 2024-12-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_remove_news_ark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('news', '新聞公告'), ('event', '活動訊息'), ('project', '徵求公告'), ('datathon', '數據松成果'), ('themeyear', '主題年活動')], max_length=10, null=True),
        ),
    ]
