# Generated by Django 4.0.4 on 2025-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
