# Generated by Django 4.0.4 on 2026-05-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_news_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='type',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('file', '檔案'), ('ext-link', '外部連結'), ('doc-link', '文件網站連結')], max_length=10, null=True),
        ),
    ]
