# Generated by Django 4.0.4 on 2026-05-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_rename_type_resource_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
