# Generated by Django 5.2.14 on 2026-06-09 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_alter_resource_created_alter_resource_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('doc_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.resource')),
            ],
            options={
                'db_table': 'resource_version',
                'ordering': ['-version'],
                'unique_together': {('resource', 'version')},
            },
        ),
    ]
