# Generated by Django 5.2.14 on 2026-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_resourceversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=10)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('key', 'lang')},
            },
        ),
    ]
