[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

    [entryPoints.websecure.http.tls]
      certResolver = "lets-encrypt"

#[api]
#  dashboard = true
#  insecure = true

[certificatesResolvers.lets-encrypt.acme]
  tlschallenge = true
  email = "zxc9830@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"

[providers.docker]
  watch = true
  network = "gateway2"
  exposedByDefault = false
[providers.file]
  #filename = "traefik_dynamic.toml"
  directory = "/dynamic_conf"


