"""
Django settings for tbia project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import environ
import os
from django.utils.translation import gettext_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Build .env to locate private settings
# https://pypi.org/project/python-environ/
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SOLR_PREFIX = env('SOLR_PREFIX')

datahub_db_settings = {
    "host": env('DATAHUB_POSTGRES_HOST'),
    "port": int(env('DATAHUB_POSTGRES_PORT')),
    "user": env('DATAHUB_POSTGRES_USER'),
    "password": env('DATAHUB_POSTGRES_PASSWORD'),
    "database": env('DATAHUB_POSTGRES_DB'),
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'pages',
    'manager',
    'data',
    'api',
    'ckeditor',
    'ckeditor_uploader',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # google provider
    'allauth.socialaccount.providers.google',
    # 'django_quill',
]

SITE_ID = 1 # oauth
# SOCIALACCOUNT_LOGIN_ON_GET=True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

SOCIALACCOUNT_ADAPTER = 'conf.adapter.MySocialAccountAdapter'


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pages.custom_context_processor.get_partners',
                'pages.custom_context_processor.get_index_partners',
                'pages.custom_context_processor.get_index_collaborates',
                'pages.custom_context_processor.today'
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL'),
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



LANGUAGES = (
    ('en-us', 'en'),
    ('zh-hant', 'zh-hant'),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATIC_ROOT = ''
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join('static'),]

default_static_dir = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATIC_ROOT = env('STATIC_ROOT', default=default_static_dir)
STATICFILES_DIRS = [default_static_dir, ]

MEDIA_URL = '/media/'
MEDIA_ROOT = env('MEDIA_ROOT')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# login
AUTH_USER_MODEL = "manager.User" 
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    "manager.views.registerBackend"
)

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

LOGIN_URL = '/login'

SESSION_COOKIE_AGE = 604800 # automatically logout after a week

# message module
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'


# email
EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_SES_REGION_NAME = env('AWS_SES_REGION_NAME', default='')
AWS_SES_REGION_ENDPOINT = env('AWS_SES_REGION_ENDPOINT', default='')



CKEDITOR_UPLOAD_PATH = "uploads/"

# CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'

# CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'

# CKEDITOR_CONFIGS = {
#    'default': {
#        'height': 'full', 
#        'width': 'full', 
#        'toolbar_Full': [
#             ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
#             ['Link', 'Unlink', 'Anchor'],
#             ['Image', 'Flash', 'Table', 'HorizontalRule'],
#             ['TextColor', 'BGColor'],
#             ['Smiley', 'SpecialChar'], ['Source'],
#             ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
#             ['NumberedList','BulletedList'],
#             ['Indent','Outdent'],
#             ['Maximize'],
#             # ['Save', 'NewPage', 'Preview', 'Print', '-', 'Templates'],
#         ],
#         'extraPlugins': 'justify,liststyle,indent',
#    },
# }


DATA_UPLOAD_MAX_MEMORY_SIZE = 20*1024*1024



CSRF_TRUSTED_ORIGINS = ['https://dev.tbiadata.tw','https://tbiadata.tw']



# Content Security Policy 
CSP_DEFAULT_SRC = ("'self'",) 
CSP_FRAME_SRC = ("'self'","https://www.google.com/","https://www.youtube.com/") 
CSP_CONNECT_SRC = ("'self'","https://www.google-analytics.com/","https://analytics.google.com/","https://stats.g.doubleclick.net/","https://accounts.google.com/o/oauth2/auth") 
CSP_STYLE_SRC = ["'self'",
    "https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css",
    "https://unpkg.com/leaflet@1.7.1/dist/leaflet.css",
    "https://fonts.googleapis.com/",
    "https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css",
    "https://cdn.quilljs.com/1.3.6/quill.snow.css",
    "https://unpkg.com/leaflet-gesture-handling@1.2.2/dist/leaflet-gesture-handling.min.css"
]

# CSP_IMG_SRC = ("'self'","*","data: *") 
CSP_IMG_SRC = ("'self'",
               "data: http://www.w3.org/2000/svg",
               # 地圖
               "https://a.tile.osm.org/",
               "https://b.tile.osm.org/",
               "https://c.tile.osm.org/",
               "https://www.googletagmanager.com/",
               "https://cdnjs.cloudflare.com/ajax/libs/leaflet/",
               "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/",
               "https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/",
               # 生命大百科
               "https://data.taieol.tw/",
               # 各單位資料    
            #    "https://www.tbn.org.tw/", 
            #    "https://n2t.net/",
            #    "https://brmas-media.s3.ap-northeast-1.amazonaws.com/"
               ) 

CSP_MEDIA_SRC = ("'self'") 
CSP_STATIC_SRC = ("'self'") 
CSP_FORM_ACTION = ("'self'","https://accounts.google.com/") 
# CSP_FORM_ACTION = ("'self'","*") 
CSP_FRAME_ANCESTORS = ("'self'") 
CSP_FONT_SRC = ("'self'",
"https://fonts.googleapis.com/",
"https://fonts.gstatic.com/"
) 

CSP_SCRIPT_SRC = ["'self'", 
    'https://www.google.com/recaptcha/api.js',
    "https://www.googletagmanager.com/",
    "https://www.google-analytics.com/",
    'https://platform.twitter.com/',
    'https://www.line-website.com/',
    "https://code.jquery.com/jquery-3.7.1.min.js",
    "https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js",
    "https://code.highcharts.com/highcharts.js",
    "https://code.highcharts.com/modules/exporting.js",
    "https://code.highcharts.com/modules/export-data.js",
    "https://code.highcharts.com/modules/accessibility.js",
    "https://code.highcharts.com/modules/treemap.js",
    "https://unpkg.com/leaflet@1.7.1/dist/leaflet.js", 
    "data: http://www.w3.org/2000/svg", 
    "https://www.gstatic.com/",
    'https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js',
    "https://unpkg.com/@turf/turf@6/turf.min.js",
    # "'unsafe-inline'",
    "https://cdn.quilljs.com/1.3.6/quill.js",
    "https://unpkg.com/terraformer@1.0.7/terraformer.js",
    "https://unpkg.com/terraformer-wkt-parser@1.1.2/terraformer-wkt-parser.js",
    "https://unpkg.com/leaflet-gesture-handling@1.2.2/dist/leaflet-gesture-handling.min.js"
]

# <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

