# Generated by Django 3.2.10 on 2022-01-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20220121_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unit',
            new_name='partner',
        ),
    ]
