# Generated by Django 3.2.10 on 2022-09-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20220921_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.partner'),
        ),
    ]
