# Generated by Django 3.2.10 on 2022-09-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
