# Generated by Django 3.2.10 on 2022-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_partner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
