# Generated by Django 3.2.10 on 2022-09-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_partnerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
