# Generated by Django 3.2.10 on 2022-10-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_sensitivedatarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_status',
            field=models.CharField(blank=True, choices=[('pending', '等待審核'), ('pass', '通過'), ('fail', '不通過'), ('withdraw', '撤回')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PartnerRequest',
        ),
    ]
