# Generated by Django 3.2.10 on 2022-10-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20221007_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='partner_status',
            new_name='status',
        ),
    ]
