# Generated by Django 3.2.10 on 2022-10-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_rename_partner_status_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
