# Generated by Django 3.2.10 on 2022-10-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_searchquery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='download_times',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
