# Generated by Django 3.2.10 on 2022-10-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20221026_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='modified',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
