# Generated by Django 3.2.10 on 2022-10-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_searchquery_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='modified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
