# Generated by Django 3.2.10 on 2022-10-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20221026_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='query_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
