# Generated by Django 3.2.10 on 2022-10-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_searchquery_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensitivedatarequest',
            name='partner_coverage',
        ),
        migrations.RemoveField(
            model_name='sensitivedatarequest',
            name='user',
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='query_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '處理中'), ('pass', '完成'), ('fail', '失敗'), ('expired', '過期')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensitivedatarequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '等待審核'), ('pass', '通過'), ('fail', '不通過')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
