# Generated by Django 3.2.10 on 2022-10-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_auto_20221027_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensitivedatarequest',
            old_name='comment',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='applicant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='project_affiliation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='project_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='type',
            field=models.CharField(blank=True, choices=[('pending', '等待審核'), ('pass', '通過'), ('fail', '不通過')], max_length=20),
        ),
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='users',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SensitiveDataResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=1000)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', '等待審核'), ('pass', '通過'), ('fail', '不通過')], max_length=20)),
                ('query_id', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.partner')),
            ],
        ),
    ]
