# Generated by Django 3.2.10 on 2022-10-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_auto_20221028_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivedataresponse',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
