# Generated by Django 3.2.10 on 2022-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_sensitivedataresponse_is_transferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensitivedatarequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='sensitivedatarequest',
            name='type',
            field=models.CharField(blank=True, choices=[('pending', '等待審核'), ('pass', '通過'), ('fail', '不通過'), ('partial', '部分通過')], max_length=20),
        ),
    ]
