# Generated by Django 3.2.10 on 2022-11-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_auto_20221101_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivedatarequest',
            name='type',
            field=models.CharField(blank=True, choices=[(0, '個人研究計畫'), (1, '委辦工作計畫')], max_length=20),
        ),
    ]
