# Generated by Django 3.2.10 on 2023-04-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_partner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrenceID', models.CharField(blank=True, max_length=1000)),
                ('tbiaID', models.CharField(blank=True, max_length=50)),
                ('sourceScientificName', models.CharField(blank=True, max_length=1000)),
                ('is_matched', models.BooleanField()),
                ('taxonID', models.CharField(blank=True, max_length=20, null=True)),
                ('parentTaxonID', models.CharField(blank=True, max_length=20, null=True)),
                ('match_stage', models.CharField(blank=True, max_length=5, null=True)),
                ('stage_1', models.CharField(blank=True, max_length=20, null=True)),
                ('stage_2', models.CharField(blank=True, max_length=20, null=True)),
                ('stage_3', models.CharField(blank=True, max_length=20, null=True)),
                ('stage_4', models.CharField(blank=True, max_length=20, null=True)),
                ('stage_5', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
