# Generated by Django 3.2.10 on 2023-04-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_matchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlog',
            name='sourceScientificName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
