# Generated by Django 3.2.10 on 2023-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_matchlog_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='select_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
