# Generated by Django 3.2.10 on 2023-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_searchquery_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='index_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
