# Generated by Django 4.0.4 on 2023-12-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_partner_breadtitle_en_partner_select_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='breadtitle',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='breadtitle_en',
        ),
    ]
