# Generated by Django 4.0.4 on 2023-12-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_remove_partner_breadtitle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchLog',
        ),
    ]
