# Generated by Django 4.0.4 on 2023-12-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_delete_matchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_method',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
