# Generated by Django 4.0.4 on 2024-01-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_user_register_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_location', models.CharField(blank=True, choices=[('full', '全站搜尋'), ('occ', '物種出現紀錄進階搜尋'), ('col', '自然史典藏進階搜尋')], max_length=20)),
                ('query', models.TextField(blank=True, null=True)),
                ('stat', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchquery',
            name='stat',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
