# Generated by Django 4.0.4 on 2024-01-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_searchstat_searchquery_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstat',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
