# Generated by Django 4.0.4 on 2024-01-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_alter_searchstat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstat',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
