# Generated by Django 4.0.4 on 2024-01-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_alter_searchstat_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_location', models.CharField(blank=True, choices=[('api_occ', '物種出現紀錄API')], max_length=20)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='searchstat',
            name='search_location',
            field=models.CharField(blank=True, choices=[('full', '全站搜尋'), ('occ', '物種出現紀錄進階搜尋'), ('col', '自然史典藏進階搜尋'), ('api_occ', '物種出現紀錄API')], max_length=20),
        ),
    ]
