# Generated by Django 4.0.4 on 2024-01-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0055_searchcount_alter_searchstat_search_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
