# Generated by Django 4.0.4 on 2024-01-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_alter_searchcount_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcount',
            name='created',
        ),
    ]
