# Generated by Django 4.0.4 on 2024-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_remove_searchcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivedatarequest',
            name='type',
            field=models.CharField(blank=True, choices=[('0', '個人研究計畫'), ('1', '委辦工作計畫')], max_length=20),
        ),
    ]
