# Generated by Django 4.0.4 on 2024-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0058_alter_sensitivedatarequest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
                ('count', models.JSONField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('month', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
