# Generated by Django 4.0.4 on 2024-04-09 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0059_keywordstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordstat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 9, 5, 53, 21, 538487, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchstat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
