# Generated by Django 4.0.4 on 2024-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0060_alter_keywordstat_created_alter_searchstat_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordstat',
            name='month',
        ),
        migrations.RemoveField(
            model_name='keywordstat',
            name='year',
        ),
        migrations.AddField(
            model_name='keywordstat',
            name='year_month',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
