# Generated by Django 4.0.4 on 2024-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0061_remove_keywordstat_month_remove_keywordstat_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('count', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('data', '累積資料數量'), ('search', '累積被查詢資料數量'), ('download', '累積被下載資料數量')], db_index=True, max_length=20)),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rights_holder', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('year_month', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('count', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('taxon_group', '物種類群'), ('family', '科別')], db_index=True, max_length=20)),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rights_holder', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('year_month', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('count', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
