# Generated by Django 4.0.4 on 2024-04-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0062_checkliststat_datastat_taxonstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonstat',
            old_name='created',
            new_name='modified',
        ),
    ]
