# Generated by Django 4.0.4 on 2024-04-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0063_rename_created_taxonstat_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkliststat',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastat',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywordstat',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxonstat',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
