# Generated by Django 4.0.4 on 2024-04-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_alter_checkliststat_count_alter_datastat_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastat',
            name='count',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
