# Generated by Django 4.0.4 on 2024-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_sensitivedatarequest_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='is_agreeed_report',
            field=models.BooleanField(default=False),
        ),
    ]
