# Generated by Django 4.0.4 on 2024-05-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_sensitivedatarequest_is_agreeed_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensitivedatarequest',
            old_name='is_agreeed_report',
            new_name='is_agreed_report',
        ),
    ]
