# Generated by Django 4.0.4 on 2024-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0069_sensitivedataresponse_is_partial_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_collaborate_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_collaborate_admin',
            field=models.BooleanField(default=False),
        ),
    ]
