# Generated by Django 4.0.4 on 2024-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0070_user_is_collaborate_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_collaborate',
            field=models.BooleanField(default=False),
        ),
    ]
