# Generated by Django 4.0.4 on 2024-07-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0071_partner_is_collaborate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='is_collaborate',
            new_name='is_collaboration',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_collaborate_account',
            new_name='is_collaboration_account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_collaborate_admin',
            new_name='is_collaboration_admin',
        ),
    ]
