# Generated by Django 4.0.4 on 2024-07-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0072_rename_is_collaborate_partner_is_collaboration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_collaboration_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_collaboration_admin',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='sensitive_stat',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
