# Generated by Django 4.0.4 on 2024-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0073_remove_user_is_collaboration_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='principal_investigator',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
