# Generated by Django 4.0.4 on 2024-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0077_ark_remove_searchquery_ark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonstat',
            name='year_month',
        ),
        migrations.AddField(
            model_name='taxonstat',
            name='month',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='taxonstat',
            name='year',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='datastat',
            name='type',
            field=models.CharField(blank=True, choices=[('data', '累積資料數量'), ('search', '累積被查詢資料數量'), ('download', '累積被下載資料數量'), ('search_times', '累積被查詢次數'), ('download_times', '累積被下載次數'), ('sensitive', '累積敏感資料被下載筆數')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='taxonstat',
            name='type',
            field=models.CharField(blank=True, choices=[('taxon_group', '物種類群'), ('family', '科別'), ('temporal', '時間空缺')], db_index=True, max_length=20),
        ),
    ]
