# Generated by Django 4.0.4 on 2025-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0079_alter_taxonstat_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ark',
            name='modified',
        ),
        migrations.AlterField(
            model_name='searchcount',
            name='search_location',
            field=models.CharField(blank=True, choices=[('api_occ', '物種出現紀錄API'), ('dataset', '資料集API')], max_length=20),
        ),
    ]
