# Generated by Django 4.0.4 on 2025-09-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0081_sensitivedatareport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivedatarequest',
            name='research_proposal',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
