# Generated by Django 4.0.4 on 2025-12-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0082_sensitivedatarequest_research_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('affiliation', '所屬單位'), ('role', '身份'), ('purpose', '使用用途')], db_index=True, max_length=20)),
                ('year_month', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
