# Generated by Django 4.0.4 on 2025-12-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0083_userstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='option',
            field=models.CharField(blank=True, choices=[('a1', '民間公司'), ('a2', 'NGO'), ('a3', '學術單位及大專院校'), ('a4', '國高中及小學'), ('a5', '政府單位'), ('a6', '自然史典藏單位'), ('a7', '其他'), ('b1', '學生'), ('b2', '教職人員'), ('b3', '公務人員'), ('b4', '研究相關從事人員（如：研究助理）'), ('b5', '環境顧問業人員'), ('b6', '外包資訊廠商人員'), ('b7', '其他工商業人員'), ('b8', '非營利組織人員'), ('b9', '其他'), ('c1', '生態/環社檢核或環境影響評估/監測'), ('c2', '永續發展或企業責任指標應用（如SDGs/ESG）'), ('c3', '推廣、寫作或應用競賽活動'), ('c4', '展覽或展示設計'), ('c5', '生態系服務或棲地復育評估'), ('c6', '政策規劃'), ('c7', '環境教育教材'), ('c8', '生態相關領域研究'), ('c9', '其他領域研究'), ('c10', '學校課程作業'), ('c11', '其他')], db_index=True, max_length=20),
        ),
    ]
