# Generated by Django 4.0.4 on 2025-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0084_userstat_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userstat',
            name='rights_holder',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
