# Generated by Django 4.0.4 on 2025-12-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0085_userstat_group_userstat_rights_holder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStat',
            new_name='UserDownloadStat',
        ),
    ]
