# Generated by Django 4.0.4 on 2025-12-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0086_rename_userstat_userdownloadstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='user_stat',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
