# Generated by Django 4.0.4 on 2026-01-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0087_searchquery_user_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivedataresponse',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
