# Generated by Django 4.0.4 on 2026-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0088_sensitivedataresponse_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivedataresponse',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
