# Generated by Django 4.0.4 on 2026-05-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0089_alter_sensitivedataresponse_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivedatarequest',
            name='type',
            field=models.CharField(blank=True, choices=[('0', '個人研究計畫'), ('1', '委辦工作或補助計畫')], max_length=20),
        ),
    ]
