# Generated by Django 5.2.14 on 2026-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0090_alter_sensitivedatarequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastat',
            name='type',
            field=models.CharField(blank=True, choices=[('data', '累積資料數量'), ('search', '累積被查詢資料數量'), ('download', '累積被下載資料數量'), ('search_times', '累積被查詢次數'), ('download_times', '累積被下載次數'), ('sensitive', '累積敏感資料被下載筆數'), ('ark', 'ARK申請次數')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='searchcount',
            name='search_location',
            field=models.CharField(blank=True, choices=[('api_occ', '物種出現紀錄API'), ('api_dataset', '資料集API'), ('api_map', '地圖API')], max_length=20),
        ),
        migrations.AlterField(
            model_name='searchstat',
            name='search_location',
            field=models.CharField(blank=True, choices=[('full', '全站搜尋'), ('occ', '物種出現紀錄進階搜尋'), ('col', '自然史典藏進階搜尋'), ('api_occ', '物種出現紀錄API'), ('api_map', '地圖API'), ('api_dataset', '資料集API'), ('dataset', '資料集搜尋')], max_length=20),
        ),
    ]
