# Generated by Django 5.2.14 on 2026-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0091_alter_datastat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='has_detail_page',
            field=models.BooleanField(default=True),
        ),
    ]
