# Generated by Django 5.2.14 on 2026-09-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0092_partner_has_detail_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rights_holder', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('year_month', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('axis', models.CharField(blank=True, db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('responsibility', models.CharField(blank=True, max_length=20, null=True)),
                ('records', models.IntegerField(blank=True, null=True)),
                ('unique_names', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
