# Generated by Django 5.2.14 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0093_matchstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=100)),
                ('year_month', models.CharField(db_index=True, max_length=20)),
                ('prev_year_month', models.CharField(blank=True, max_length=20, null=True)),
                ('logic_changed', models.BooleanField(default=False)),
                ('compare', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='matchstat',
            name='category_key',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
